# UniLearn Hub


# Controls 
#1. who can connect
#2. from where
#3. how


# Rules checked in order


# TYPE    DATABASE   USER   ADDRESS            METHOD

# this machine, local socket (app server running alongside the DB)
local     all        all                       scram-sha-256

# A machine on the network (in this case the local machiine bcs of 127... loopback TCP) must still authenticate w password
hostssl   all        all    127.0.0.1/32       scram-sha-256
hostssl   all        all    ::1/128            scram-sha-256

# app-tier subnet only, not the whole internal network
hostssl   unilearn   all    10.20.1.0/24       scram-sha-256

# explicitly reject everything else -- the database is not reachable
# from the open internet
host      all        all    0.0.0.0/0          reject
host      all        all    ::/0               reject